import { readdirSync, readFileSync, writeFileSync } from "node:fs"
import path from "node:path"
import { z } from "zod"

const configSchema = z.object({
  description: z.string().trim().min(1),
  label: z.string().trim().min(1),
  path: z.enum([
    "AGENTS.md",
    "HEARTBEAT.md",
    "IDENTITY.md",
    "MEMORY.md",
    "SOUL.md",
    "USER.md",
    "TOOLS.md",
  ]),
  sortOrder: z.number().int().nonnegative(),
})

const packageRoot = path.resolve(import.meta.dirname, "..")
const sourceRoot = path.join(packageRoot, "src", "managed-config", "files")
const outputPath = path.join(
  packageRoot,
  "src",
  "managed-config",
  "generated-managed-config.ts",
)

const definitions = readdirSync(sourceRoot)
  .filter((entryName) => {
    return !entryName.startsWith(".")
  })
  .map((entryName) => {
    const entryPath = path.join(sourceRoot, entryName)
    const config = configSchema.parse(
      JSON.parse(readFileSync(path.join(entryPath, "config.json"), "utf8")),
    )

    return {
      ...config,
      defaultSharedContent: readFileSync(
        path.join(entryPath, "workspace.md"),
        "utf8",
      ).trim(),
      systemContent: readFileSync(
        path.join(entryPath, "system.md"),
        "utf8",
      ).trim(),
    }
  })
  .sort(
    (left, right) =>
      left.sortOrder - right.sortOrder || left.path.localeCompare(right.path),
  )
  .map(({ sortOrder: _sortOrder, ...definition }) => definition)

const source = [
  "// biome-ignore-all format: generated file is written by the managed-config generator.",
  'import type { ManagedBootstrapFileDefinition } from "./definition"',
  "",
  "// Generated by packages/features/runtime-core/scripts/generate-managed-config.ts.",
  "// Do not edit this file directly. Edit files under src/managed-config/files instead.",
  "export const GENERATED_MANAGED_BOOTSTRAP_FILE_DEFINITIONS =",
  `  ${JSON.stringify(definitions, null, 2)} as const satisfies readonly ManagedBootstrapFileDefinition[]`,
  "",
].join("\n")

writeFileSync(outputPath, source)
