import { mkdirSync, writeFileSync } from "node:fs"
import path from "node:path"
import { fileURLToPath } from "node:url"

import { loadSystemManagedSkillDefinitionsFromDirectory } from "../src/managed-skills/file-library"

const packageRoot = path.resolve(
  path.dirname(fileURLToPath(import.meta.url)),
  "..",
)
const libraryRoot = path.join(packageRoot, "src", "managed-skills", "library")
const generatedPath = path.join(
  packageRoot,
  "src",
  "managed-skills",
  "generated-system-skills.ts",
)

const definitions = loadSystemManagedSkillDefinitionsFromDirectory(libraryRoot)
const generatedContent = [
  "// biome-ignore-all format: generated file is written by the managed-skills generator.",
  "// biome-ignore-all lint/suspicious/noTemplateCurlyInString: generated skill files may contain literal code examples.",
  'import type { SystemManagedSkillDefinition } from "./system-skills"',
  "",
  "// Generated by packages/features/runtime-core/scripts/generate-managed-skills.ts.",
  "// Do not edit this file directly. Edit files under src/managed-skills/library instead.",
  "export const SYSTEM_MANAGED_SKILL_DEFINITIONS =",
  `  ${JSON.stringify(definitions, null, 2).replace(/\n/g, "\n  ")} as const satisfies readonly SystemManagedSkillDefinition[]`,
  "",
].join("\n")

mkdirSync(path.dirname(generatedPath), { recursive: true })
writeFileSync(generatedPath, generatedContent)
